public class savingsgeneralaccwrapper {
        public String Id{get;set;}
        public String MeetingOf{get;set;}
        public String MeetingHeldAt{get;set;}
        public Date MeetingDate{get;set;}
        public Date Extractsigneddate{get;set;}
        public integer Totalnumofaccountstobeopened{get;set;}
        public integer Requirednumberofsignatoriestoopencloseaccounts{get;set;}
        public integer Requirednumofsignatoriestogiveinstructions{get;set;}
        public String SourceofFundssavings{get;set;}
    	public String CommentsonexplanationgivenforSourceoffunds{get;set;}


}